#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUYO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PUYO_WAREHOUSE")]
	public partial class PUYOWAREHOUSEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertWarehouse_Master_Transaction(Warehouse_Master_Transaction instance);
    partial void UpdateWarehouse_Master_Transaction(Warehouse_Master_Transaction instance);
    partial void DeleteWarehouse_Master_Transaction(Warehouse_Master_Transaction instance);
    partial void InsertWarehouse_Product(Warehouse_Product instance);
    partial void UpdateWarehouse_Product(Warehouse_Product instance);
    partial void DeleteWarehouse_Product(Warehouse_Product instance);
    partial void InsertWarehouse_Product_Type(Warehouse_Product_Type instance);
    partial void UpdateWarehouse_Product_Type(Warehouse_Product_Type instance);
    partial void DeleteWarehouse_Product_Type(Warehouse_Product_Type instance);
    partial void InsertWarehouse_Store(Warehouse_Store instance);
    partial void UpdateWarehouse_Store(Warehouse_Store instance);
    partial void DeleteWarehouse_Store(Warehouse_Store instance);
    partial void InsertWarehouse_Transaction(Warehouse_Transaction instance);
    partial void UpdateWarehouse_Transaction(Warehouse_Transaction instance);
    partial void DeleteWarehouse_Transaction(Warehouse_Transaction instance);
    #endregion
		
		public PUYOWAREHOUSEDataContext() : 
				base(global::PUYO.Properties.Settings.Default.PUYO_WAREHOUSEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PUYOWAREHOUSEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PUYOWAREHOUSEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PUYOWAREHOUSEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PUYOWAREHOUSEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Warehouse_Master_Transaction> Warehouse_Master_Transactions
		{
			get
			{
				return this.GetTable<Warehouse_Master_Transaction>();
			}
		}
		
		public System.Data.Linq.Table<Warehouse_Product> Warehouse_Products
		{
			get
			{
				return this.GetTable<Warehouse_Product>();
			}
		}
		
		public System.Data.Linq.Table<Warehouse_Product_Type> Warehouse_Product_Types
		{
			get
			{
				return this.GetTable<Warehouse_Product_Type>();
			}
		}
		
		public System.Data.Linq.Table<Warehouse_Store> Warehouse_Stores
		{
			get
			{
				return this.GetTable<Warehouse_Store>();
			}
		}
		
		public System.Data.Linq.Table<Warehouse_Transaction> Warehouse_Transactions
		{
			get
			{
				return this.GetTable<Warehouse_Transaction>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Warehouse_Master_Transaction")]
	public partial class Warehouse_Master_Transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Master_Transaction_ID;
		
		private System.DateTime _Master_Transaction_Date;
		
		private string _Store_ID;
		
		private EntitySet<Warehouse_Transaction> _Warehouse_Transactions;
		
		private EntityRef<Warehouse_Store> _Warehouse_Store;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaster_Transaction_IDChanging(string value);
    partial void OnMaster_Transaction_IDChanged();
    partial void OnMaster_Transaction_DateChanging(System.DateTime value);
    partial void OnMaster_Transaction_DateChanged();
    partial void OnStore_IDChanging(string value);
    partial void OnStore_IDChanged();
    #endregion
		
		public Warehouse_Master_Transaction()
		{
			this._Warehouse_Transactions = new EntitySet<Warehouse_Transaction>(new Action<Warehouse_Transaction>(this.attach_Warehouse_Transactions), new Action<Warehouse_Transaction>(this.detach_Warehouse_Transactions));
			this._Warehouse_Store = default(EntityRef<Warehouse_Store>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Master_Transaction_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Master_Transaction_ID
		{
			get
			{
				return this._Master_Transaction_ID;
			}
			set
			{
				if ((this._Master_Transaction_ID != value))
				{
					this.OnMaster_Transaction_IDChanging(value);
					this.SendPropertyChanging();
					this._Master_Transaction_ID = value;
					this.SendPropertyChanged("Master_Transaction_ID");
					this.OnMaster_Transaction_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Master_Transaction_Date", DbType="Date NOT NULL")]
		public System.DateTime Master_Transaction_Date
		{
			get
			{
				return this._Master_Transaction_Date;
			}
			set
			{
				if ((this._Master_Transaction_Date != value))
				{
					this.OnMaster_Transaction_DateChanging(value);
					this.SendPropertyChanging();
					this._Master_Transaction_Date = value;
					this.SendPropertyChanged("Master_Transaction_Date");
					this.OnMaster_Transaction_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Store_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Store_ID
		{
			get
			{
				return this._Store_ID;
			}
			set
			{
				if ((this._Store_ID != value))
				{
					if (this._Warehouse_Store.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStore_IDChanging(value);
					this.SendPropertyChanging();
					this._Store_ID = value;
					this.SendPropertyChanged("Store_ID");
					this.OnStore_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Warehouse_Master_Transaction_Warehouse_Transaction", Storage="_Warehouse_Transactions", ThisKey="Master_Transaction_ID", OtherKey="Master_Transaction_ID")]
		public EntitySet<Warehouse_Transaction> Warehouse_Transactions
		{
			get
			{
				return this._Warehouse_Transactions;
			}
			set
			{
				this._Warehouse_Transactions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Warehouse_Store_Warehouse_Master_Transaction", Storage="_Warehouse_Store", ThisKey="Store_ID", OtherKey="Store_ID", IsForeignKey=true)]
		public Warehouse_Store Warehouse_Store
		{
			get
			{
				return this._Warehouse_Store.Entity;
			}
			set
			{
				Warehouse_Store previousValue = this._Warehouse_Store.Entity;
				if (((previousValue != value) 
							|| (this._Warehouse_Store.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Warehouse_Store.Entity = null;
						previousValue.Warehouse_Master_Transactions.Remove(this);
					}
					this._Warehouse_Store.Entity = value;
					if ((value != null))
					{
						value.Warehouse_Master_Transactions.Add(this);
						this._Store_ID = value.Store_ID;
					}
					else
					{
						this._Store_ID = default(string);
					}
					this.SendPropertyChanged("Warehouse_Store");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Warehouse_Transactions(Warehouse_Transaction entity)
		{
			this.SendPropertyChanging();
			entity.Warehouse_Master_Transaction = this;
		}
		
		private void detach_Warehouse_Transactions(Warehouse_Transaction entity)
		{
			this.SendPropertyChanging();
			entity.Warehouse_Master_Transaction = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Warehouse_Product")]
	public partial class Warehouse_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Product_ID;
		
		private string _Product_Type_ID;
		
		private string _Product_Name;
		
		private decimal _Product_Price;
		
		private EntitySet<Warehouse_Transaction> _Warehouse_Transactions;
		
		private EntityRef<Warehouse_Product_Type> _Warehouse_Product_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduct_IDChanging(string value);
    partial void OnProduct_IDChanged();
    partial void OnProduct_Type_IDChanging(string value);
    partial void OnProduct_Type_IDChanged();
    partial void OnProduct_NameChanging(string value);
    partial void OnProduct_NameChanged();
    partial void OnProduct_PriceChanging(decimal value);
    partial void OnProduct_PriceChanged();
    #endregion
		
		public Warehouse_Product()
		{
			this._Warehouse_Transactions = new EntitySet<Warehouse_Transaction>(new Action<Warehouse_Transaction>(this.attach_Warehouse_Transactions), new Action<Warehouse_Transaction>(this.detach_Warehouse_Transactions));
			this._Warehouse_Product_Type = default(EntityRef<Warehouse_Product_Type>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this.OnProduct_IDChanging(value);
					this.SendPropertyChanging();
					this._Product_ID = value;
					this.SendPropertyChanged("Product_ID");
					this.OnProduct_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Type_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Product_Type_ID
		{
			get
			{
				return this._Product_Type_ID;
			}
			set
			{
				if ((this._Product_Type_ID != value))
				{
					if (this._Warehouse_Product_Type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProduct_Type_IDChanging(value);
					this.SendPropertyChanging();
					this._Product_Type_ID = value;
					this.SendPropertyChanged("Product_Type_ID");
					this.OnProduct_Type_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Product_Name
		{
			get
			{
				return this._Product_Name;
			}
			set
			{
				if ((this._Product_Name != value))
				{
					this.OnProduct_NameChanging(value);
					this.SendPropertyChanging();
					this._Product_Name = value;
					this.SendPropertyChanged("Product_Name");
					this.OnProduct_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Price", DbType="Decimal(18,0) NOT NULL")]
		public decimal Product_Price
		{
			get
			{
				return this._Product_Price;
			}
			set
			{
				if ((this._Product_Price != value))
				{
					this.OnProduct_PriceChanging(value);
					this.SendPropertyChanging();
					this._Product_Price = value;
					this.SendPropertyChanged("Product_Price");
					this.OnProduct_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Warehouse_Product_Warehouse_Transaction", Storage="_Warehouse_Transactions", ThisKey="Product_ID", OtherKey="Product_ID")]
		public EntitySet<Warehouse_Transaction> Warehouse_Transactions
		{
			get
			{
				return this._Warehouse_Transactions;
			}
			set
			{
				this._Warehouse_Transactions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Warehouse_Product_Type_Warehouse_Product", Storage="_Warehouse_Product_Type", ThisKey="Product_Type_ID", OtherKey="Product_Type_ID", IsForeignKey=true)]
		public Warehouse_Product_Type Warehouse_Product_Type
		{
			get
			{
				return this._Warehouse_Product_Type.Entity;
			}
			set
			{
				Warehouse_Product_Type previousValue = this._Warehouse_Product_Type.Entity;
				if (((previousValue != value) 
							|| (this._Warehouse_Product_Type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Warehouse_Product_Type.Entity = null;
						previousValue.Warehouse_Products.Remove(this);
					}
					this._Warehouse_Product_Type.Entity = value;
					if ((value != null))
					{
						value.Warehouse_Products.Add(this);
						this._Product_Type_ID = value.Product_Type_ID;
					}
					else
					{
						this._Product_Type_ID = default(string);
					}
					this.SendPropertyChanged("Warehouse_Product_Type");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Warehouse_Transactions(Warehouse_Transaction entity)
		{
			this.SendPropertyChanging();
			entity.Warehouse_Product = this;
		}
		
		private void detach_Warehouse_Transactions(Warehouse_Transaction entity)
		{
			this.SendPropertyChanging();
			entity.Warehouse_Product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Warehouse_Product_Type")]
	public partial class Warehouse_Product_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Product_Type_ID;
		
		private string _Product_Type_Name;
		
		private EntitySet<Warehouse_Product> _Warehouse_Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduct_Type_IDChanging(string value);
    partial void OnProduct_Type_IDChanged();
    partial void OnProduct_Type_NameChanging(string value);
    partial void OnProduct_Type_NameChanged();
    #endregion
		
		public Warehouse_Product_Type()
		{
			this._Warehouse_Products = new EntitySet<Warehouse_Product>(new Action<Warehouse_Product>(this.attach_Warehouse_Products), new Action<Warehouse_Product>(this.detach_Warehouse_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Type_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Product_Type_ID
		{
			get
			{
				return this._Product_Type_ID;
			}
			set
			{
				if ((this._Product_Type_ID != value))
				{
					this.OnProduct_Type_IDChanging(value);
					this.SendPropertyChanging();
					this._Product_Type_ID = value;
					this.SendPropertyChanged("Product_Type_ID");
					this.OnProduct_Type_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Type_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Product_Type_Name
		{
			get
			{
				return this._Product_Type_Name;
			}
			set
			{
				if ((this._Product_Type_Name != value))
				{
					this.OnProduct_Type_NameChanging(value);
					this.SendPropertyChanging();
					this._Product_Type_Name = value;
					this.SendPropertyChanged("Product_Type_Name");
					this.OnProduct_Type_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Warehouse_Product_Type_Warehouse_Product", Storage="_Warehouse_Products", ThisKey="Product_Type_ID", OtherKey="Product_Type_ID")]
		public EntitySet<Warehouse_Product> Warehouse_Products
		{
			get
			{
				return this._Warehouse_Products;
			}
			set
			{
				this._Warehouse_Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Warehouse_Products(Warehouse_Product entity)
		{
			this.SendPropertyChanging();
			entity.Warehouse_Product_Type = this;
		}
		
		private void detach_Warehouse_Products(Warehouse_Product entity)
		{
			this.SendPropertyChanging();
			entity.Warehouse_Product_Type = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Warehouse_Store")]
	public partial class Warehouse_Store : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Store_ID;
		
		private string _Store_Location;
		
		private EntitySet<Warehouse_Master_Transaction> _Warehouse_Master_Transactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStore_IDChanging(string value);
    partial void OnStore_IDChanged();
    partial void OnStore_LocationChanging(string value);
    partial void OnStore_LocationChanged();
    #endregion
		
		public Warehouse_Store()
		{
			this._Warehouse_Master_Transactions = new EntitySet<Warehouse_Master_Transaction>(new Action<Warehouse_Master_Transaction>(this.attach_Warehouse_Master_Transactions), new Action<Warehouse_Master_Transaction>(this.detach_Warehouse_Master_Transactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Store_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Store_ID
		{
			get
			{
				return this._Store_ID;
			}
			set
			{
				if ((this._Store_ID != value))
				{
					this.OnStore_IDChanging(value);
					this.SendPropertyChanging();
					this._Store_ID = value;
					this.SendPropertyChanged("Store_ID");
					this.OnStore_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Store_Location", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Store_Location
		{
			get
			{
				return this._Store_Location;
			}
			set
			{
				if ((this._Store_Location != value))
				{
					this.OnStore_LocationChanging(value);
					this.SendPropertyChanging();
					this._Store_Location = value;
					this.SendPropertyChanged("Store_Location");
					this.OnStore_LocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Warehouse_Store_Warehouse_Master_Transaction", Storage="_Warehouse_Master_Transactions", ThisKey="Store_ID", OtherKey="Store_ID")]
		public EntitySet<Warehouse_Master_Transaction> Warehouse_Master_Transactions
		{
			get
			{
				return this._Warehouse_Master_Transactions;
			}
			set
			{
				this._Warehouse_Master_Transactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Warehouse_Master_Transactions(Warehouse_Master_Transaction entity)
		{
			this.SendPropertyChanging();
			entity.Warehouse_Store = this;
		}
		
		private void detach_Warehouse_Master_Transactions(Warehouse_Master_Transaction entity)
		{
			this.SendPropertyChanging();
			entity.Warehouse_Store = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Warehouse_Transaction")]
	public partial class Warehouse_Transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Transaction_ID;
		
		private string _Product_ID;
		
		private string _Master_Transaction_ID;
		
		private int _Quantity;
		
		private decimal _Total_Price;
		
		private string _Status;
		
		private EntityRef<Warehouse_Master_Transaction> _Warehouse_Master_Transaction;
		
		private EntityRef<Warehouse_Product> _Warehouse_Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransaction_IDChanging(string value);
    partial void OnTransaction_IDChanged();
    partial void OnProduct_IDChanging(string value);
    partial void OnProduct_IDChanged();
    partial void OnMaster_Transaction_IDChanging(string value);
    partial void OnMaster_Transaction_IDChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnTotal_PriceChanging(decimal value);
    partial void OnTotal_PriceChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public Warehouse_Transaction()
		{
			this._Warehouse_Master_Transaction = default(EntityRef<Warehouse_Master_Transaction>);
			this._Warehouse_Product = default(EntityRef<Warehouse_Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Transaction_ID
		{
			get
			{
				return this._Transaction_ID;
			}
			set
			{
				if ((this._Transaction_ID != value))
				{
					this.OnTransaction_IDChanging(value);
					this.SendPropertyChanging();
					this._Transaction_ID = value;
					this.SendPropertyChanged("Transaction_ID");
					this.OnTransaction_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					if (this._Warehouse_Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProduct_IDChanging(value);
					this.SendPropertyChanging();
					this._Product_ID = value;
					this.SendPropertyChanged("Product_ID");
					this.OnProduct_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Master_Transaction_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Master_Transaction_ID
		{
			get
			{
				return this._Master_Transaction_ID;
			}
			set
			{
				if ((this._Master_Transaction_ID != value))
				{
					if (this._Warehouse_Master_Transaction.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaster_Transaction_IDChanging(value);
					this.SendPropertyChanging();
					this._Master_Transaction_ID = value;
					this.SendPropertyChanged("Master_Transaction_ID");
					this.OnMaster_Transaction_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Price", DbType="Decimal(18,0) NOT NULL")]
		public decimal Total_Price
		{
			get
			{
				return this._Total_Price;
			}
			set
			{
				if ((this._Total_Price != value))
				{
					this.OnTotal_PriceChanging(value);
					this.SendPropertyChanging();
					this._Total_Price = value;
					this.SendPropertyChanged("Total_Price");
					this.OnTotal_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Warehouse_Master_Transaction_Warehouse_Transaction", Storage="_Warehouse_Master_Transaction", ThisKey="Master_Transaction_ID", OtherKey="Master_Transaction_ID", IsForeignKey=true)]
		public Warehouse_Master_Transaction Warehouse_Master_Transaction
		{
			get
			{
				return this._Warehouse_Master_Transaction.Entity;
			}
			set
			{
				Warehouse_Master_Transaction previousValue = this._Warehouse_Master_Transaction.Entity;
				if (((previousValue != value) 
							|| (this._Warehouse_Master_Transaction.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Warehouse_Master_Transaction.Entity = null;
						previousValue.Warehouse_Transactions.Remove(this);
					}
					this._Warehouse_Master_Transaction.Entity = value;
					if ((value != null))
					{
						value.Warehouse_Transactions.Add(this);
						this._Master_Transaction_ID = value.Master_Transaction_ID;
					}
					else
					{
						this._Master_Transaction_ID = default(string);
					}
					this.SendPropertyChanged("Warehouse_Master_Transaction");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Warehouse_Product_Warehouse_Transaction", Storage="_Warehouse_Product", ThisKey="Product_ID", OtherKey="Product_ID", IsForeignKey=true)]
		public Warehouse_Product Warehouse_Product
		{
			get
			{
				return this._Warehouse_Product.Entity;
			}
			set
			{
				Warehouse_Product previousValue = this._Warehouse_Product.Entity;
				if (((previousValue != value) 
							|| (this._Warehouse_Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Warehouse_Product.Entity = null;
						previousValue.Warehouse_Transactions.Remove(this);
					}
					this._Warehouse_Product.Entity = value;
					if ((value != null))
					{
						value.Warehouse_Transactions.Add(this);
						this._Product_ID = value.Product_ID;
					}
					else
					{
						this._Product_ID = default(string);
					}
					this.SendPropertyChanged("Warehouse_Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
