//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUYO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PUYO_WAREHOUSE_RESTOCK1_ENTITY : DbContext
    {
        public PUYO_WAREHOUSE_RESTOCK1_ENTITY()
            : base("name=PUYO_WAREHOUSE_RESTOCK1_ENTITY")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<RESTOCKING_Result> RESTOCKING(string storeID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var storeIDParameter = storeID != null ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RESTOCKING_Result>("RESTOCKING", storeIDParameter, fromDateParameter, toDateParameter);
        }
    }
}
